Class {
	#name : #CMUnknownSourceLanguage,
	#superclass : #CMSourceLanguage,
	#traits : 'FamixTUnknownSourceLanguage',
	#classTraits : 'FamixTUnknownSourceLanguage classTrait',
	#category : #'Cormas-Entities-Entities'
}

{ #category : #meta }
CMUnknownSourceLanguage class >> annotation [

	<FMClass: #UnknownSourceLanguage super: #CMSourceLanguage>
	<package: #'Cormas-Entities'>
	<generated>
	^ self
]
